[workspace]
members = [
    "paper-quota-applet",
    "logout-applet",
    "theme-applet",
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.metadata.crane]
name = "ocf-cosmic-applets"
